name: async_test
description: Async tests with DoneFn completion, where the test does not end, until the finisher is called
version: 0.0.1
homepage: https://polytope.dk
author: Bogi N. W. <bogi@polytope.dk>

environment:
  sdk: '>=3.1.2'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
